name: Rerender PDFs

on:
  push:
    branches: master
  pull_request:
    branches: master

  workflow_dispatch:

jobs:
  render_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - run: sudo apt-get update

      - name: install svg to png
        run: sudo apt-get install librsvg2-bin

      - name: create list of all files
        id: files_list
        run: |
          cd md
          echo "files=$(printf '"md/%s" ' *.md)" >> $GITHUB_ENV

      - name: print all files
        run: echo compiling ${{ env.files }}

      - name: create docs folder if not exists
        run: mkdir -p docs

      - name: compile and merge summary
        uses: docker://pandoc/latex:2.9
        with:
          args: -V documentclass=report -V classoption=oneside -V geometry:vmargin=14.5mm -V lang:de --fail-if-warnings --output=docs/summary.pdf ${{ env.files }}

      - uses: actions/upload-artifact@master
        with:
          name: summary.pdf
          path: docs/summary.pdf

  render_slides:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: install pdftk
        run: sudo apt-get install pdftk

      - name: create docs folder if not exists
        run: mkdir -p docs

      - name: merge
        run: pdftk slides/*.pdf cat output docs/slides.pdf

      - uses: actions/upload-artifact@master
        with:
          name: slides.pdf
          path: docs/slides.pdf

  push_merged_pdfs:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [render_summary, render_slides]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master

      - name: delete old pdfs if exists
        run: rm -f docs/*.pdf

      - uses: actions/download-artifact@master
        with:
          name: slides.pdf
          path: docs

      - uses: actions/download-artifact@master
        with:
          name: summary.pdf
          path: docs

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rerendered PDFs
